name: Check markdown dead links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@master
    - name: Checking for dead links
      uses: gaurav-nelson/github-action-markdown-link-check@v1